In [87]:
import multiprocessing
import scanpy as sc
import squidpy as sq

def run_ligrec(adata):
    # all your parameters here
    return sq.gr.ligrec(
        adata,
        n_perms=200,
        cluster_key="assigned_celltype_L0",
        copy=True,
        use_raw=False,
        transmitter_params={"categories": "ligand"},
        receiver_params={"categories": "receptor"}
    )

if __name__ == "__main__":
        multiprocessing.freeze_support()

        #adata = sq.datasets.seqfish()
        #adata = sc.read_h5ad("/Volumes/ProstateCancerEvoMain/dbs/Ongoing/Collection/MajorAnnGroups/Epithelia_SubTypes/Region1.Epithelia_SubTypes.AnnDC.h5ad")
        adata = sc.read_h5ad("/Volumes/ProstateCancerEvoMain/up-to-date/ProstateCancerEvo_SpatialAnalysis/scripts/spatial_aware_analysis/spatial_interactions/R1_MiddleLoc.h5ad")


        res = run_ligrec(adata)
res

  0%|          | 0/200 [00:00<?, ?permutation/s]/Users/ugursahin/miniforge3/envs/ScanPy2/lib/python3.12/site-packages/numba/parfors/parfor.py:2395: NumbaPerformanceWarning:


prange or pndindex loop will not be executed in parallel due to there being more than one entry to or exit from the loop (e.g., an assertion).

File "/Volumes/ProstateCancerEvoMain/up-to-date/ProstateCancerEvo_SpatialAnalysis/scripts/spatial_aware_analysis/spatial_interactions", line 33:
<source missing, REPL/exec in use?>


/Users/ugursahin/miniforge3/envs/ScanPy2/lib/python3.12/site-packages/dask/dataframe/__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
  warnings.warn(
/Users/ugursahin/miniforge3/envs/ScanPy2/lib/python3.12/site-packages/xarray_schema/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
/Users/ugursahin/miniforge3/envs/ScanPy2/lib/python3.12/site-packages/anndata/utils.py:434: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
100%|██████████| 200/200 [08:26<00:00,  2.53s/permutation]

{'means': cluster_1     CD4 T Cell                                                     \
 cluster_2     CD4 T Cell CD8 T Cell        DC Macrophage_M2 Mast Neutrophil
 source target
 EPOR   TRPC3           0          0         0             0    0          0
 FYN    TRPC4           0          0         0             0    0          0
        TRPC6           0          0         0             0    0          0
        TRPV4           0   0.334145  0.339748             0    0          0
        TRPV6           0          0         0             0    0          0
 ...                  ...        ...       ...           ...  ...        ...
 IFNG   GRIA1           0          0         0             0    0          0
 CXCL12 ESR2            0          0         0             0    0          0
 FYN    F2R      0.340912   0.472858         0             0    0          0
 IL1B   NR2C2           0          0         0      0.012491    0          0
 FYN    GRM1     0.343916   0.341481  0.355603      0.363192    0          0

 cluster_1                                                              \
 cluster_2     Plasma_Cell   Unknown basal_cell_of_prostate_epithelium
 source target
 EPOR   TRPC3            0         0                                 0
 FYN    TRPC4            0         0                                 0
        TRPC6            0  0.330273                                 0
        TRPV4            0         0                                 0
        TRPV6            0         0                            0.3337
 ...                   ...       ...                               ...
 IFNG   GRIA1            0  0.007043                                 0
 CXCL12 ESR2             0         0                                 0
 FYN    F2R        0.41279  0.397774                                 0
 IL1B   NR2C2     0.019626         0                          0.016592
 FYN    GRM1      0.336826         0                                 0

 cluster_1                                              ... tumor_cell_markers  \
 cluster_2     basal_epithelial_cell_of_prostatic_duct  ...            Unknown
 source target                                          ...
 EPOR   TRPC3                                        0  ...            0.02397
 FYN    TRPC4                                        0  ...                  0
        TRPC6                                 0.354553  ...                  0
        TRPV4                                 0.431188  ...                  0
        TRPV6                                 0.349619  ...                  0
 ...                                               ...  ...                ...
 IFNG   GRIA1                                        0  ...                  0
 CXCL12 ESR2                                         0  ...                  0
 FYN    F2R                                          0  ...                  0
 IL1B   NR2C2                                 0.023149  ...                  0
 FYN    GRM1                                         0  ...                  0

 cluster_1                                        \
 cluster_2     basal_cell_of_prostate_epithelium
 source target
 EPOR   TRPC3                                  0
 FYN    TRPC4                                  0
        TRPC6                                  0
        TRPV4                                  0
        TRPV6                                  0
 ...                                         ...
 IFNG   GRIA1                                  0
 CXCL12 ESR2                                   0
 FYN    F2R                                    0
 IL1B   NR2C2                                  0
 FYN    GRM1                                   0

 cluster_1                                              \
 cluster_2     basal_epithelial_cell_of_prostatic_duct
 source target
 EPOR   TRPC3                                        0
 FYN    TRPC4                                        0
        TRPC6                                        0
        TRPV4                                        0
        TRPV6                                        0
 ...                                               ...
 IFNG   GRIA1                                        0
 CXCL12 ESR2                                         0
 FYN    F2R                                          0
 IL1B   NR2C2                                        0
 FYN    GRM1                                         0

 cluster_1                                                                    \
 cluster_2     fibroblast_of_connective_tissue_of_glandular_part_of_prostate
 source target
 EPOR   TRPC3                                            0.008641
 FYN    TRPC4                                                   0
        TRPC6                                                   0
        TRPV4                                                   0
        TRPV6                                                   0
 ...                                                          ...
 IFNG   GRIA1                                                   0
 CXCL12 ESR2                                                    0
 FYN    F2R                                                     0
 IL1B   NR2C2                                                   0
 FYN    GRM1                                                    0

 cluster_1                                                                       \
 cluster_2     fibroblast_of_connective_tissue_of_nonglandular_part_of_prostate
 source target
 EPOR   TRPC3                                                   0
 FYN    TRPC4                                                   0
        TRPC6                                                   0
        TRPV4                                                   0
        TRPV6                                                   0
 ...                                                          ...
 IFNG   GRIA1                                                   0
 CXCL12 ESR2                                                    0
 FYN    F2R                                                     0
 IL1B   NR2C2                                                   0
 FYN    GRM1                                                    0

 cluster_1                           \
 cluster_2     neuron_cell pericyte
 source target
 EPOR   TRPC3            0        0
 FYN    TRPC4            0        0
        TRPC6            0        0
        TRPV4            0        0
        TRPV6            0        0
 ...                   ...      ...
 IFNG   GRIA1            0        0
 CXCL12 ESR2             0        0
 FYN    F2R              0        0
 IL1B   NR2C2            0        0
 FYN    GRM1             0        0

 cluster_1                                                    \
 cluster_2     prostate_gland_microvascular_endothelial_cell
 source target
 EPOR   TRPC3                                              0
 FYN    TRPC4                                              0
        TRPC6                                              0
        TRPV4                                              0
        TRPV6                                              0
 ...                                                     ...
 IFNG   GRIA1                                              0
 CXCL12 ESR2                                               0
 FYN    F2R                                                0
 IL1B   NR2C2                                              0
 FYN    GRM1                                               0

 cluster_1
 cluster_2     smooth_muscle_cell_of_prostate tumor_cell_markers
 source target
 EPOR   TRPC3                        0.049769                  0
 FYN    TRPC4                               0                  0
        TRPC6                               0                  0
        TRPV4                               0                  0
        TRPV6                               0                  0
 ...                                      ...                ...
 IFNG   GRIA1                               0                  0
 CXCL12 ESR2                                0                  0
 FYN    F2R                                 0                  0
 IL1B   NR2C2                               0                  0
 FYN    GRM1                                0                  0

 [5249 rows x 289 columns],
 'pvalues': cluster_1     CD4 T Cell                                                \
 cluster_2     CD4 T Cell CD8 T Cell   DC Macrophage_M2 Mast Neutrophil
 source target
 EPOR   TRPC3         NaN        NaN  NaN           NaN  NaN        NaN
 FYN    TRPC4         NaN        NaN  NaN           NaN  NaN        NaN
        TRPC6         NaN        NaN  NaN           NaN  NaN        NaN
        TRPV4         NaN        NaN  NaN           NaN  NaN        NaN
        TRPV6         NaN        NaN  NaN           NaN  NaN        NaN
 ...                  ...        ...  ...           ...  ...        ...
 IFNG   GRIA1         NaN        NaN  NaN           NaN  NaN        NaN
 CXCL12 ESR2          NaN        NaN  NaN           NaN  NaN        NaN
 FYN    F2R           NaN        NaN  NaN           NaN  NaN        NaN
 IL1B   NR2C2         NaN        NaN  NaN           NaN  NaN        NaN
 FYN    GRM1          NaN        NaN  NaN           NaN  NaN        NaN

 cluster_1                                                            \
 cluster_2     Plasma_Cell Unknown basal_cell_of_prostate_epithelium
 source target
 EPOR   TRPC3          NaN     NaN                               NaN
 FYN    TRPC4          NaN     NaN                               NaN
        TRPC6          NaN     NaN                               NaN
        TRPV4          NaN     NaN                               NaN
        TRPV6          NaN     NaN                               NaN
 ...                   ...     ...                               ...
 IFNG   GRIA1          NaN     NaN                               NaN
 CXCL12 ESR2           NaN     NaN                               NaN
 FYN    F2R            NaN     NaN                               NaN
 IL1B   NR2C2          NaN     NaN                               NaN
 FYN    GRM1           NaN     NaN                               NaN

 cluster_1                                              ... tumor_cell_markers  \
 cluster_2     basal_epithelial_cell_of_prostatic_duct  ...            Unknown
 source target                                          ...
 EPOR   TRPC3                                      NaN  ...                NaN
 FYN    TRPC4                                      NaN  ...                NaN
        TRPC6                                      NaN  ...                NaN
        TRPV4                                      NaN  ...                NaN
        TRPV6                                      NaN  ...                NaN
 ...                                               ...  ...                ...
 IFNG   GRIA1                                      NaN  ...                NaN
 CXCL12 ESR2                                       NaN  ...                NaN
 FYN    F2R                                        NaN  ...                NaN
 IL1B   NR2C2                                      NaN  ...                NaN
 FYN    GRM1                                       NaN  ...                NaN

 cluster_1                                        \
 cluster_2     basal_cell_of_prostate_epithelium
 source target
 EPOR   TRPC3                                NaN
 FYN    TRPC4                                NaN
        TRPC6                                NaN
        TRPV4                                NaN
        TRPV6                                NaN
 ...                                         ...
 IFNG   GRIA1                                NaN
 CXCL12 ESR2                                 NaN
 FYN    F2R                                  NaN
 IL1B   NR2C2                                NaN
 FYN    GRM1                                 NaN

 cluster_1                                              \
 cluster_2     basal_epithelial_cell_of_prostatic_duct
 source target
 EPOR   TRPC3                                      NaN
 FYN    TRPC4                                      NaN
        TRPC6                                      NaN
        TRPV4                                      NaN
        TRPV6                                      NaN
 ...                                               ...
 IFNG   GRIA1                                      NaN
 CXCL12 ESR2                                       NaN
 FYN    F2R                                        NaN
 IL1B   NR2C2                                      NaN
 FYN    GRM1                                       NaN

 cluster_1                                                                    \
 cluster_2     fibroblast_of_connective_tissue_of_glandular_part_of_prostate
 source target
 EPOR   TRPC3                                                 NaN
 FYN    TRPC4                                                 NaN
        TRPC6                                                 NaN
        TRPV4                                                 NaN
        TRPV6                                                 NaN
 ...                                                          ...
 IFNG   GRIA1                                                 NaN
 CXCL12 ESR2                                                  NaN
 FYN    F2R                                                   NaN
 IL1B   NR2C2                                                 NaN
 FYN    GRM1                                                  NaN

 cluster_1                                                                       \
 cluster_2     fibroblast_of_connective_tissue_of_nonglandular_part_of_prostate
 source target
 EPOR   TRPC3                                                 NaN
 FYN    TRPC4                                                 NaN
        TRPC6                                                 NaN
        TRPV4                                                 NaN
        TRPV6                                                 NaN
 ...                                                          ...
 IFNG   GRIA1                                                 NaN
 CXCL12 ESR2                                                  NaN
 FYN    F2R                                                   NaN
 IL1B   NR2C2                                                 NaN
 FYN    GRM1                                                  NaN

 cluster_1                           \
 cluster_2     neuron_cell pericyte
 source target
 EPOR   TRPC3          NaN      NaN
 FYN    TRPC4          NaN      NaN
        TRPC6          NaN      NaN
        TRPV4          NaN      NaN
        TRPV6          NaN      NaN
 ...                   ...      ...
 IFNG   GRIA1          NaN      NaN
 CXCL12 ESR2           NaN      NaN
 FYN    F2R            NaN      NaN
 IL1B   NR2C2          NaN      NaN
 FYN    GRM1           NaN      NaN

 cluster_1                                                    \
 cluster_2     prostate_gland_microvascular_endothelial_cell
 source target
 EPOR   TRPC3                                            NaN
 FYN    TRPC4                                            NaN
        TRPC6                                            NaN
        TRPV4                                            NaN
        TRPV6                                            NaN
 ...                                                     ...
 IFNG   GRIA1                                            NaN
 CXCL12 ESR2                                             NaN
 FYN    F2R                                              NaN
 IL1B   NR2C2                                            NaN
 FYN    GRM1                                             NaN

 cluster_1
 cluster_2     smooth_muscle_cell_of_prostate tumor_cell_markers
 source target
 EPOR   TRPC3                             NaN                NaN
 FYN    TRPC4                             NaN                NaN
        TRPC6                             NaN                NaN
        TRPV4                             NaN                NaN
        TRPV6                             NaN                NaN
 ...                                      ...                ...
 IFNG   GRIA1                             NaN                NaN
 CXCL12 ESR2                              NaN                NaN
 FYN    F2R                               NaN                NaN
 IL1B   NR2C2                             NaN                NaN
 FYN    GRM1                              NaN                NaN

 [5249 rows x 289 columns],
 'metadata':               aspect_intercell_source aspect_intercell_target  \
 source target
 EPOR   TRPC3               functional              functional
 FYN    TRPC4               functional              functional
        TRPC6               functional              functional
        TRPV4               functional              functional
        TRPV6               functional              functional
 ...                               ...                     ...
 IFNG   GRIA1               functional              functional
 CXCL12 ESR2                functional              functional
 FYN    F2R                 functional              functional
 IL1B   NR2C2               functional              functional
 FYN    GRM1                functional              functional

               category_intercell_source category_intercell_target  \
 source target
 EPOR   TRPC3                     ligand                  receptor
 FYN    TRPC4                     ligand                  receptor
        TRPC6                     ligand                  receptor
        TRPV4                     ligand                  receptor
        TRPV6                     ligand                  receptor
 ...                                 ...                       ...
 IFNG   GRIA1                     ligand                  receptor
 CXCL12 ESR2                      ligand                  receptor
 FYN    F2R                       ligand                  receptor
 IL1B   NR2C2                     ligand                  receptor
 FYN    GRM1                      ligand                  receptor

               category_source_intercell_source  \
 source target
 EPOR   TRPC3                 resource_specific
 FYN    TRPC4                 resource_specific
        TRPC6                 resource_specific
        TRPV4                 resource_specific
        TRPV6                 resource_specific
 ...                                        ...
 IFNG   GRIA1                 resource_specific
 CXCL12 ESR2                  resource_specific
 FYN    F2R                   resource_specific
 IL1B   NR2C2                 resource_specific
 FYN    GRM1                  resource_specific

               category_source_intercell_target  consensus_direction  \
 source target
 EPOR   TRPC3                 resource_specific                 True
 FYN    TRPC4                 resource_specific                False
        TRPC6                 resource_specific                 True
        TRPV4                 resource_specific                 True
        TRPV6                 resource_specific                 True
 ...                                        ...                  ...
 IFNG   GRIA1                 resource_specific                False
 CXCL12 ESR2                  resource_specific                False
 FYN    F2R                   resource_specific                False
 IL1B   NR2C2                 resource_specific                False
 FYN    GRM1                  resource_specific                False

                consensus_inhibition  consensus_score_intercell_source  \
 source target
 EPOR   TRPC3                  False                                 1
 FYN    TRPC4                  False                                 2

In [91]:
res["means"]['CD8 T Cell']

cluster_2      CD4 T Cell  CD8 T Cell        DC  Macrophage_M2  Mast  \
source target
EPOR   TRPC3            0           0         0              0     0
FYN    TRPC4            0           0         0              0     0
       TRPC6            0           0         0              0     0
       TRPV4            0    0.650015  0.655618              0     0
       TRPV6            0           0         0              0     0
...                   ...         ...       ...            ...   ...
IFNG   GRIA1            0           0         0              0     0
CXCL12 ESR2             0           0         0              0     0
FYN    F2R       0.656782    0.788727         0              0     0
IL1B   NR2C2            0           0         0              0     0
FYN    GRM1      0.659785    0.657351  0.671473       0.679062     0

cluster_2      Neutrophil  Plasma_Cell   Unknown  \
source target
EPOR   TRPC3            0            0         0
FYN    TRPC4            0            0         0
       TRPC6            0            0  0.646143
       TRPV4            0            0         0
       TRPV6            0            0         0
...                   ...          ...       ...
IFNG   GRIA1            0            0  0.116599
CXCL12 ESR2             0            0         0
FYN    F2R              0      0.72866  0.713644
IL1B   NR2C2            0            0         0
FYN    GRM1             0     0.652696         0

cluster_2      basal_cell_of_prostate_epithelium  \
source target
EPOR   TRPC3                                   0
FYN    TRPC4                                   0
       TRPC6                                   0
       TRPV4                                   0
       TRPV6                             0.64957
...                                          ...
IFNG   GRIA1                                   0
CXCL12 ESR2                                    0
FYN    F2R                                     0
IL1B   NR2C2                                   0
FYN    GRM1                                    0

cluster_2      basal_epithelial_cell_of_prostatic_duct  \
source target
EPOR   TRPC3                                         0
FYN    TRPC4                                         0
       TRPC6                                  0.670423
       TRPV4                                  0.747058
       TRPV6                                  0.665489
...                                                ...
IFNG   GRIA1                                         0
CXCL12 ESR2                                          0
FYN    F2R                                           0
IL1B   NR2C2                                         0
FYN    GRM1                                          0

cluster_2      fibroblast_of_connective_tissue_of_glandular_part_of_prostate  \
source target
EPOR   TRPC3                                                   0
FYN    TRPC4                                            0.802948
       TRPC6                                             0.69994
       TRPV4                                                   0
       TRPV6                                                   0
...                                                          ...
IFNG   GRIA1                                                   0
CXCL12 ESR2                                                    0
FYN    F2R                                               1.09262
IL1B   NR2C2                                                   0
FYN    GRM1                                             0.646971

cluster_2      fibroblast_of_connective_tissue_of_nonglandular_part_of_prostate  \
source target
EPOR   TRPC3                                                   0
FYN    TRPC4                                                   0
       TRPC6                                                   0
       TRPV4                                                   0
       TRPV6                                                   0
...                                                          ...
IFNG   GRIA1                                                   0
CXCL12 ESR2                                                    0
FYN    F2R                                                     0
IL1B   NR2C2                                                   0
FYN    GRM1                                                    0

cluster_2      neuron_cell  pericyte  \
source target
EPOR   TRPC3             0         0
FYN    TRPC4             0  0.732094
       TRPC6             0  0.830048
       TRPV4             0         0
       TRPV6             0         0
...                    ...       ...
IFNG   GRIA1      0.165948  0.138913
CXCL12 ESR2              0         0
FYN    F2R         0.79568  0.710524
IL1B   NR2C2             0         0
FYN    GRM1              0  0.652524

cluster_2      prostate_gland_microvascular_endothelial_cell  \
source target
EPOR   TRPC3                                               0
FYN    TRPC4                                               0
       TRPC6                                               0
       TRPV4                                        0.662193
       TRPV6                                               0
...                                                      ...
IFNG   GRIA1                                        0.141311
CXCL12 ESR2                                                0
FYN    F2R                                          0.911631
IL1B   NR2C2                                               0
FYN    GRM1                                                0

cluster_2      smooth_muscle_cell_of_prostate  tumor_cell_markers
source target
EPOR   TRPC3                                0                   0
FYN    TRPC4                         0.927472                   0
       TRPC6                         0.835134                   0
       TRPV4                                0                   0
       TRPV6                                0            0.761089
...                                       ...                 ...
IFNG   GRIA1                                0                   0
CXCL12 ESR2                                 0                   0
FYN    F2R                                  0                   0
IL1B   NR2C2                                0                   0
FYN    GRM1                                 0                   0

[5249 rows x 17 columns]

In [92]:
df_plot = res["means"]['CD8 T Cell']["tumor_cell_markers"].rename("value").reset_index()
df_plot

      source target     value
0       EPOR  TRPC3         0
1        FYN  TRPC4         0
2        FYN  TRPC6         0
3        FYN  TRPV4         0
4        FYN  TRPV6  0.761089
...      ...    ...       ...
5244    IFNG  GRIA1         0
5245  CXCL12   ESR2         0
5246     FYN    F2R         0
5247    IL1B  NR2C2         0
5248     FYN   GRM1         0

[5249 rows x 3 columns]

In [93]:
import pandas as pd
import plotly.express as px

# 3. Bubble‐plot with Plotly
fig = px.scatter(
    df_plot,
    x="target",
    y="source",
    size="value",
    color="value",
    color_continuous_scale="Blues",
    size_max=20,
    hover_data=["value"],
    labels={"value": "Score"},
    width=1600,
    height=1000
)
fig.update_layout(
    xaxis_tickangle=45,
    yaxis=dict(tickfont=dict(size=8)),
    plot_bgcolor="white",
    margin=dict(l=200, r=20, t=50, b=200)
)
fig.show()